<?php

/**
 * @file
 * 
 * This module This module holds the custom functions that compute some fields for the County node.
 */

/**
 * Callback function for enrollment_total field on County node.
 * 
 * @param $entity_field
 * @param $entity_type
 * @param $entity
 * @param $field
 * @param $instance
 * @param $langcode
 * @param $items
 */
function computed_field_field_enrollment_total_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  // Add all enrollment fields to an array.
  $enrollment_fields = array(
    'field_enrollment_business',
    'field_enrollment_dentistry',
    'field_enrollment_education',
    'field_enrollment_engineering',
    'field_enrollment_graduate',
    'field_enrollment_law',
    'field_enrollment_clas',
    'field_enrollment_medicine',
    'field_enrollment_nursing',
    'field_enrollment_pharmacy',
    'field_enrollment_public_health',
  );
  
  // Calculate the total enrollment.
  $enrollment_total = _field_compute_sum($entity_type, $entity, $enrollment_fields);
  
  // Assign the total to the field.
  $entity_field[0]['value'] = $enrollment_total; 
}

/**
 * Helper function to sum an array of fields of integer type.
 * 
 * @param $entity_type
 * @param $entity
 * @param $fields
 */
function _field_compute_sum($entity_type, $entity, $fields) {
  $total = 0;
  foreach ($fields as $field) {
    $total += array_pop(array_pop(field_get_items($entity_type, $entity, $field)));
  }
  
  return $total;
}