<?php
/**
 * @file
 * This module handles the applicaiton logic for the Outreach maps.
 */

/**
 * Implements template_preprocess_page().
 *
 * @param $variables
 */
function outreach_maps_preprocess_page(&$variables) {
  // The county map is the default map for the front page.
  if ($variables['is_front'] == TRUE) {
    // Get the path to the module.
    $path = drupal_get_path('module', 'outreach_maps');

    // Add the necessary scripts.
    drupal_add_js('http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.js', array('type' => 'external', 'group' => JS_LIBRARY, 'weight' => '98'));
    drupal_add_js($path . '/js/counties.jquery.js', array('weight' => '99'));

    // Add default styles for controls.
    drupal_add_css('http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.css', array('type' => 'external'));
  }
}

/**
 * Implements hook_menu().
 *
 * @return array items
 */
function outreach_maps_menu() {
  $items['/outreach-maps/county/%'] = array(
    'page_callback' => '_outreach_maps_load_county',
    'page_arguments' => array(2),
  );

  return $items;
}

/**
 * Helper function to return county data.
 *
 * @param  string $county
 * @return array  $data
 */
function _outreach_maps_load_county($county, $type = 'ajax') {
  $data = array();

  // Build an EFQ that returns a county node;
  $county_query = new EntityFieldQuery();
  $county_query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'county')
  ->propertyCondition('title', $county);

  // Execute the query.
  $county_result = $county_query->execute();

  return $data;
}
