<?php
/**
 * @file
 * This module handles the applicaiton logic for the Outreach maps.
 */

/**
 * Implements template_preprocess_page().
 *
 * @param $variables
 */
function outreach_maps_preprocess_page(&$variables) {
  // The county map is the default map for the front page.
  if ($variables['is_front'] == TRUE) {
    // Get the path to the module.
    $path = drupal_get_path('module', 'outreach_maps');

    // Add the necessary scripts.
    drupal_add_js('http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.js', array('type' => 'external', 'group' => JS_LIBRARY, 'weight' => '90'));
    drupal_add_js($path . '/js/counties.jquery.js', array('weight' => '91'));
    drupal_add_js('misc/ajax.js', array('weight' => '92'));

    // Add default styles for controls.
    drupal_add_css('http://api.tiles.mapbox.com/mapbox.js/v0.6.6/mapbox.css', array('type' => 'external'));
  }
}

/**
 * Implements hook_menu().
 *
 * @return array items
 */
function outreach_maps_menu() {
   $items = array();

  // A menu callback is required when using ajax outside of the Form API.
  $items['outreach-maps/county/%'] = array(
    'page callback' => '_outreach_maps_load_county',
    'page arguments' => array(2),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'outreach_maps.callbacks.inc',
);

  return $items;
}
